version: "3"
services:
  dotnet:
    build:
      dockerfile: ci/docker/linux.Dockerfile
      context: ../../
    command: ["ci/docker/entrypoint.sh", "ci/test.sh"]
    volumes:
        - ${IMPROBABLE_CONFIG_DIR}:/home/user/.improbable
        - ${LOGS_DIR}:/build/worker/config/logs
        - ${TEST_RESULTS_DIR}:/build/worker/test-results
    environment:
        - TEST_RESULTS_DIR=/build/worker/test-results
	
