version: "3"
services:
  dotnet:
    build:
      dockerfile: ci/docker/linux.Dockerfile
      context: ../../
    volumes:
        - ${IMPROBABLE_CONFIG_DIR}:/var/spatial_oauth
        - ${NUGET_PACKAGE_DIR}:nupkgs
    environment:
        - IMPROBABLE_CONFIG_DIR=/var/spatial_oauth/
