version: "3"
services:
  dotnet:
    build:
      dockerfile: ci/docker/linux.Dockerfile
      context: ../../
    command: ["ci/docker/entrypoint.sh", "ci/test.sh"]
    volumes:
        - ${IMPROBABLE_CONFIG_DIR}:/var/spatial_oauth
        - ${NUGET_PACKAGE_DIR}:/build/worker/nupkgs
    environment:
        - IMPROBABLE_CONFIG_DIR=/var/spatial_oauth/
